# Generated by Django 5.0.4 on 2024-05-01 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('helpInfo', '0001_initial'),
        ('passport', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PacsMO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namePacsMO', models.CharField(blank=True, max_length=25, null=True, verbose_name='Наименование')),
                ('modelPacsMO', models.CharField(blank=True, max_length=25, null=True, verbose_name='Модель')),
                ('inventoryPacsMO', models.CharField(blank=True, max_length=25, null=True, verbose_name='инвентарный номер')),
                ('passportMO', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='passport.passportmo')),
            ],
            options={
                'verbose_name': 'PACS',
                'verbose_name_plural': 'PACS',
            },
        ),
        migrations.CreateModel(
            name='PopulationServedMO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('territoryMO', models.CharField(blank=True, max_length=25, null=True, verbose_name='Территория')),
                ('cityMO', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='helpInfo.city', verbose_name='Город')),
                ('districtMO', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='helpInfo.district', verbose_name='Район')),
                ('passportMO', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='passport.passportmo')),
                ('settlementMO', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='helpInfo.settlement', verbose_name='Населенный пункт')),
            ],
            options={
                'verbose_name': 'Обслуживаемое население',
                'verbose_name_plural': 'Обслуживаемое население',
            },
        ),
        migrations.CreateModel(
            name='TransportMO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameTransMO', models.CharField(blank=True, max_length=25, null=True, verbose_name='Наименование')),
                ('modelConsMO', models.CharField(blank=True, max_length=25, null=True, verbose_name='Производитель')),
                ('modelTransMO', models.CharField(blank=True, max_length=25, null=True, verbose_name='Модель')),
                ('dateCons', models.DateField(blank=True, null=True, verbose_name='Дата выпуска')),
                ('dateBuy', models.DateField(blank=True, null=True, verbose_name='Дата приобретения')),
                ('consumerMD', models.CharField(blank=True, max_length=25, null=True, verbose_name='Поставщик')),
                ('regNoMO', models.CharField(blank=True, max_length=16, null=True, verbose_name='Регистрационный номер')),
                ('driveNoMD', models.CharField(blank=True, max_length=14, null=True, verbose_name='Номер двигателя')),
                ('dateUse', models.DateField(blank=True, null=True, verbose_name='Дата ввода в эксплуатацию')),
                ('costTransMO', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Стоимость приобретения')),
                ('costLastMO', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Остаточная стоимость')),
                ('passportMO', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='passport.passportmo')),
            ],
            options={
                'verbose_name': 'Транспорт',
                'verbose_name_plural': 'Транспорт',
            },
        ),
    ]
