# Generated by Django 5.0.4 on 2024-05-01 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('helpInfo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='passportMO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameMO', models.CharField(blank=True, max_length=29, null=True, verbose_name='Наименование МО')),
                ('shortNameMO', models.CharField(blank=True, max_length=50, null=True, verbose_name='Краткое наименование МО')),
                ('codeOUZS', models.CharField(blank=True, max_length=13, null=True, verbose_name='Код органа управления здравоохранением субъекта')),
            ],
            options={
                'verbose_name': 'Паспорт МО',
                'verbose_name_plural': 'Паспорт МО',
            },
        ),
        migrations.CreateModel(
            name='OmsMO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inDate', models.DateField(verbose_name='Дата включения')),
                ('outDate', models.DateField(verbose_name='Дата исключения')),
                ('dogovNo', models.CharField(blank=True, max_length=13, null=True, verbose_name='Номер договора')),
                ('regDate', models.DateField(verbose_name='Дата договора ')),
                ('placeCodeMO', models.CharField(blank=True, max_length=6, null=True, verbose_name='Код территории МО')),
                ('regNo', models.CharField(blank=True, max_length=13, null=True, verbose_name='Регистрационный номер МО')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Примечание к договору')),
                ('organizion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helpInfo.organizion')),
                ('passportMO', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='passport.passportmo')),
            ],
            options={
                'verbose_name': 'ОМС(Обязательное медицинское страхование)',
                'verbose_name_plural': 'ОМС(Обязательное медицинское страхование)',
            },
        ),
        migrations.CreateModel(
            name='LloMO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inDate', models.DateField(verbose_name='Дата включения')),
                ('outDate', models.DateField(verbose_name='Дата исключения')),
                ('passportMO', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='passport.passportmo')),
            ],
            options={
                'verbose_name': 'ЛЛО (Льготное лекарственное обеспечение)',
                'verbose_name_plural': 'ЛЛО (Льготное лекарственное обеспечение)',
            },
        ),
        migrations.CreateModel(
            name='identificationMO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regDate', models.DateField(verbose_name='Дата регистрации ')),
                ('docName', models.CharField(blank=True, max_length=50, null=True, verbose_name='Наименование регистрационного документа')),
                ('regNo', models.CharField(blank=True, max_length=13, null=True, verbose_name='Номер государственной регистрации.')),
                ('regNoSF', models.CharField(blank=True, max_length=13, null=True, verbose_name='Регистрационный номер в Социальном фонде КР.')),
                ('founder', models.TextField(blank=True, null=True, verbose_name='Учредитель')),
                ('beginDate', models.DateField(verbose_name='Дата начала деятельности')),
                ('endDate', models.DateField(verbose_name='Дата закрытия')),
                ('emailMO', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Адрес электронной почты')),
                ('siteMO', models.CharField(blank=True, max_length=50, null=True, verbose_name='Адрес сайта')),
                ('phoneMO', models.CharField(blank=True, max_length=13, null=True, verbose_name='Телефон')),
                ('timeWorkMO', models.CharField(blank=True, max_length=16, null=True, verbose_name='Время работы')),
                ('nameMOLVN', models.CharField(blank=True, max_length=29, null=True, verbose_name='Наименование МО для ЛВН')),
                ('addressMOLVN', models.CharField(blank=True, max_length=30, null=True, verbose_name='Адрес МО для ЛВН')),
                ('addressRegMO', models.CharField(blank=True, max_length=50, null=True, verbose_name='Юридический адрес ')),
                ('addressRealMO', models.CharField(blank=True, max_length=50, null=True, verbose_name='Фактический адрес')),
                ('INN', models.CharField(blank=True, max_length=14, null=True, verbose_name='ИНН')),
                ('OGRN', models.CharField(blank=True, max_length=14, null=True, verbose_name='ОГРН – основной государственный регистрационный номер')),
                ('rayonCoef', models.DecimalField(decimal_places=1, max_digits=2, verbose_name='Районный коэффициент')),
                ('spesStatus', models.DecimalField(decimal_places=1, max_digits=2, verbose_name='Особый статус')),
                ('buildingMO', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helpInfo.buildingmo', verbose_name='Основное здание')),
                ('govOrg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helpInfo.govorg', verbose_name='Орган, зарегистрировавший юридическое лицо')),
                ('okdp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helpInfo.okdp', verbose_name='ОКДП')),
                ('okfs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helpInfo.okfs', verbose_name='ТОКФС')),
                ('okopf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helpInfo.okopf', verbose_name='ОКОПФ')),
                ('okpo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helpInfo.okpo', verbose_name='ОКПО')),
                ('okved', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helpInfo.okved', verbose_name='ОКВЭД')),
                ('onmsz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helpInfo.onmsz', verbose_name='ОКВЭД')),
                ('organForm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helpInfo.organition_form', verbose_name='Организационная форма.')),
                ('placeForm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helpInfo.placeform', verbose_name='Территориальный признак')),
                ('typeAgeMO', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helpInfo.typeagemo', verbose_name='Тип МО по возрасту')),
                ('typeMO', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helpInfo.typemo', verbose_name='Тип МО')),
                ('passportMO', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='passport.passportmo')),
            ],
            options={
                'verbose_name': 'Идентификация',
                'verbose_name_plural': 'Идентификация',
            },
        ),
        migrations.CreateModel(
            name='DmsMO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inDate', models.DateField(verbose_name='Дата включения')),
                ('outDate', models.DateField(verbose_name='Дата исключения')),
                ('dogovNo', models.CharField(blank=True, max_length=13, null=True, verbose_name='Номер договора')),
                ('passportMO', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='passport.passportmo')),
            ],
            options={
                'verbose_name': 'ДМС (Добровольное медицинское страхование)',
                'verbose_name_plural': 'ДМС (Добровольное медицинское страхование)',
            },
        ),
        migrations.CreateModel(
            name='UchasSlujbaMO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inDate', models.DateField(verbose_name='Дата включения')),
                ('outDate', models.DateField(verbose_name='Дата исключения')),
                ('typeUshastok', models.CharField(blank=True, max_length=13, null=True, verbose_name='Тип участка ')),
                ('passportMO', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='passport.passportmo')),
            ],
            options={
                'verbose_name': 'Участковая служба',
                'verbose_name_plural': 'Участковая служба',
            },
        ),
    ]
