# Generated by Django 5.0.4 on 2024-05-01 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('passport', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildingMO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fencingBuildMO', models.BooleanField(default=True, verbose_name='Ограждение территории')),
                ('bodyguardMO', models.BooleanField(default=True, verbose_name='Наличие охраны')),
                ('metalDoorMO', models.BooleanField(default=True, verbose_name='Наличие металлических входных дверей в здание')),
                ('videoSurvMO', models.BooleanField(default=True, verbose_name='Видеонаблюдение территорий и помещений для здания')),
                ('accommodationMO', models.BooleanField(default=False, verbose_name='Проживание сопровождающих лиц')),
                ('forDisabilitiesMO', models.BooleanField(default=True, verbose_name='Приспособленность территории для пациентов с ограниченными возможностями')),
                ('latitudeMO', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Координаты: Широта')),
                ('longitudeMO', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Координаты: Долгота')),
                ('bldgMOName', models.CharField(blank=True, max_length=80, null=True, verbose_name='Общепринятое наименование корпуса')),
                ('bldgNoMO', models.CharField(blank=True, max_length=16, null=True, verbose_name='Номер корпуса')),
                ('bldgTypeMO', models.CharField(blank=True, max_length=16, null=True, verbose_name='тип лечебного корпуса')),
                ('bldgPurposeMO', models.CharField(blank=True, max_length=16, null=True, verbose_name='назначение здания')),
                ('bldgYearMO', models.IntegerField(blank=True, null=True, verbose_name='Год постройки ')),
                ('bldgSquareMO', models.DecimalField(decimal_places=2, max_digits=6, null=True, verbose_name='Общая площадь')),
                ('passportMO', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='passport.passportmo')),
            ],
            options={
                'verbose_name': 'Здание МО',
                'verbose_name_plural': 'Здания МО',
            },
        ),
        migrations.CreateModel(
            name='InfrastructureMO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('infrastructureName', models.CharField(blank=True, max_length=80, null=True, verbose_name='Наименование объекта')),
                ('infrastructureCountMO', models.IntegerField(blank=True, null=True, verbose_name='Количество объектов')),
                ('infrastructureNoMO', models.CharField(blank=True, max_length=16, null=True, verbose_name='Идентификатор участка')),
                ('passportMO', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='passport.passportmo')),
            ],
            options={
                'verbose_name': 'Объекты инфраструктуры',
                'verbose_name_plural': 'Объекты инфраструктуры',
            },
        ),
    ]
