# Generated by Django 5.0.4 on 2024-05-01 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BuildingMO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BuildingName', models.CharField(blank=True, max_length=60, null=True, verbose_name='Здания МО')),
            ],
            options={
                'verbose_name': 'Здания МО.',
                'verbose_name_plural': 'Здания МО.',
            },
        ),
        migrations.CreateModel(
            name='FRMOlevelMO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FRMOlevelMOName', models.CharField(blank=True, max_length=60, null=True, verbose_name='ФРМО. Уровень медицинской организации')),
            ],
            options={
                'verbose_name': 'ФРМО. Уровень медицинской организации',
                'verbose_name_plural': 'ФРМО. Уровень медицинской организации',
            },
        ),
        migrations.CreateModel(
            name='GovOrg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GovOrgName', models.CharField(blank=True, max_length=60, null=True, verbose_name='Орган, зарегистрировавший юридическое лицо')),
            ],
            options={
                'verbose_name': 'Орган, зарегистрировавший юридическое лицо',
                'verbose_name_plural': 'Орган, зарегистрировавший юридическое лицо',
            },
        ),
        migrations.CreateModel(
            name='JobTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobTitle', models.CharField(blank=True, max_length=60, null=True, verbose_name='Должность')),
            ],
            options={
                'verbose_name': 'Должность',
                'verbose_name_plural': 'Должность',
            },
        ),
        migrations.CreateModel(
            name='LevelMO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('levelMOName', models.CharField(blank=True, max_length=60, null=True, verbose_name='Уровень МО')),
            ],
            options={
                'verbose_name': 'Уровень МО',
                'verbose_name_plural': 'Уровень МО',
            },
        ),
        migrations.CreateModel(
            name='LevelSub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('levelSubName', models.CharField(blank=True, max_length=60, null=True, verbose_name='Уровень подчиненности')),
            ],
            options={
                'verbose_name': 'Уровень подчиненности',
                'verbose_name_plural': 'Уровень подчиненности',
            },
        ),
        migrations.CreateModel(
            name='MedDeviceKind',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medDeviceKindName', models.CharField(blank=True, max_length=60, null=True, verbose_name='Вид МИ')),
            ],
            options={
                'verbose_name': 'Вид МИ',
                'verbose_name_plural': 'Вид МИ',
            },
        ),
        migrations.CreateModel(
            name='MedDeviceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medDeviceTypeName', models.CharField(blank=True, max_length=60, null=True, verbose_name='Вид МИ')),
            ],
            options={
                'verbose_name': 'Тип МИ',
                'verbose_name_plural': 'Тип МИ',
            },
        ),
        migrations.CreateModel(
            name='MedService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medServiceName', models.CharField(blank=True, max_length=60, null=True, verbose_name='Медицинские услуги')),
            ],
            options={
                'verbose_name': 'Медицинские услуги',
                'verbose_name_plural': 'Медицинские услугии',
            },
        ),
        migrations.CreateModel(
            name='OKDP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OKDPName', models.CharField(blank=True, max_length=100, null=True, verbose_name='ОКДП – код по классификатору продукции')),
            ],
            options={
                'verbose_name': 'ОКДП – код по классификатору продукции',
                'verbose_name_plural': 'ОКДП – код по классификатору продукции',
            },
        ),
        migrations.CreateModel(
            name='OKFS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OKFSName', models.CharField(blank=True, max_length=100, null=True, verbose_name='ОКФС – код по классификатору форм собственности')),
            ],
            options={
                'verbose_name': 'ОКФС – код по классификатору форм собственности',
                'verbose_name_plural': 'ОКФС – код по классификатору форм собственности',
            },
        ),
        migrations.CreateModel(
            name='OKOPF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OKOPFName', models.CharField(blank=True, max_length=100, null=True, verbose_name='ОКОПФ – код по классификатору организационно-правовых форм')),
            ],
            options={
                'verbose_name': 'ОКОПФ – код по классификатору организационно-правовых форм',
                'verbose_name_plural': 'ОКОПФ – код по классификатору организационно-правовых форм',
            },
        ),
        migrations.CreateModel(
            name='OKPO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OKPOFName', models.CharField(blank=True, max_length=100, null=True, verbose_name='ОКПО – код по классификатору предприятий и организаций')),
            ],
            options={
                'verbose_name': 'ОКПО – код по классификатору предприятий и организаций',
                'verbose_name_plural': 'ОКПО – код по классификатору предприятий и организаций',
            },
        ),
        migrations.CreateModel(
            name='OKVED',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OKVEDName', models.CharField(blank=True, max_length=100, null=True, verbose_name='ОКВЭД – код выбирается из справочника классификатор видов экономической деятельности.')),
            ],
            options={
                'verbose_name': 'ОКВЭД – код выбирается из справочника классификатор видов экономической деятельности.',
                'verbose_name_plural': 'ОКВЭД – код выбирается из справочника классификатор видов экономической деятельности.',
            },
        ),
        migrations.CreateModel(
            name='ONMSZ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ONMSZName', models.CharField(blank=True, max_length=100, null=True, verbose_name='Код ОНМСЗ – код органа, назначающего меры социальной защиты.')),
            ],
            options={
                'verbose_name': 'Код ОНМСЗ – код органа, назначающего меры социальной защиты.',
                'verbose_name_plural': 'Код ОНМСЗ – код органа, назначающего меры социальной защиты.',
            },
        ),
        migrations.CreateModel(
            name='ORGANITION_FORM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ORGAN_FORMName', models.CharField(blank=True, max_length=60, null=True, verbose_name='Организационная форма')),
            ],
            options={
                'verbose_name': 'Организационная форма.',
                'verbose_name_plural': 'Организационная форма.',
            },
        ),
        migrations.CreateModel(
            name='Organizion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OrganizionName', models.CharField(blank=True, max_length=60, null=True, verbose_name='Организация')),
            ],
            options={
                'verbose_name': 'Организация',
                'verbose_name_plural': 'Организации',
            },
        ),
        migrations.CreateModel(
            name='PlaceForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PlaceFormName', models.CharField(blank=True, max_length=100, null=True, verbose_name='Территориальный признак')),
            ],
            options={
                'verbose_name': 'Территориальный признак',
                'verbose_name_plural': 'Территориальный признак',
            },
        ),
        migrations.CreateModel(
            name='PotentialRisk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('potenRiskName', models.CharField(blank=True, max_length=60, null=True, verbose_name='Класс потенциального риска применения')),
            ],
            options={
                'verbose_name': 'Тип МИ',
                'verbose_name_plural': 'Тип МИ',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regionName', models.CharField(blank=True, max_length=60, null=True, verbose_name='Область')),
            ],
            options={
                'verbose_name': 'Область',
                'verbose_name_plural': 'Области',
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stateName', models.CharField(blank=True, max_length=60, null=True, verbose_name='Страна')),
            ],
            options={
                'verbose_name': 'Страна',
                'verbose_name_plural': 'Страны',
            },
        ),
        migrations.CreateModel(
            name='typeAgeMO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeAgeMOName', models.CharField(blank=True, max_length=100, null=True, verbose_name='Тип МО по возрасту')),
            ],
            options={
                'verbose_name': 'Тип МО по возрасту',
                'verbose_name_plural': 'Тип МО по возрасту',
            },
        ),
        migrations.CreateModel(
            name='typeMO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeMOName', models.CharField(blank=True, max_length=100, null=True, verbose_name='Тип МО')),
            ],
            options={
                'verbose_name': 'Тип МО',
                'verbose_name_plural': 'Тип МО',
            },
        ),
        migrations.CreateModel(
            name='MedDeviceCls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medDeviceClsName', models.CharField(blank=True, max_length=60, null=True, verbose_name='Наименование МИ')),
                ('medDeviceClsModel', models.CharField(blank=True, max_length=60, null=True, verbose_name='Модель')),
                ('medDeviceClsFun', models.CharField(blank=True, max_length=60, null=True, verbose_name='Функциональное назначение')),
                ('medDeviceClsArea', models.CharField(blank=True, max_length=60, null=True, verbose_name='Область применения')),
                ('medDeviceClsScope', models.CharField(blank=True, max_length=60, null=True, verbose_name='Сфера применения')),
                ('medDeviceKind', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helpInfo.meddevicekind')),
                ('medDeviceType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helpInfo.meddevicetype')),
                ('potentialRisk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helpInfo.potentialrisk')),
            ],
            options={
                'verbose_name': 'Класс медицинского изделия',
                'verbose_name_plural': 'Класс медицинского изделия',
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('districtName', models.CharField(blank=True, max_length=60, null=True, verbose_name='Область')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helpInfo.region')),
            ],
            options={
                'verbose_name': 'Район',
                'verbose_name_plural': 'Район',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cityName', models.CharField(blank=True, max_length=60, null=True, verbose_name='Область')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helpInfo.region')),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Город',
            },
        ),
        migrations.CreateModel(
            name='Settlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SettlementName', models.CharField(blank=True, max_length=60, null=True, verbose_name='Область')),
                ('settlementType', models.IntegerField(choices=[(None, '(Пусто)'), (0, 'Городской'), (1, 'Сельский')], default=1, verbose_name='Тип населенного пункта')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helpInfo.district')),
            ],
            options={
                'verbose_name': 'Населенный пункт',
                'verbose_name_plural': 'Населенный пункт',
            },
        ),
        migrations.AddField(
            model_name='region',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helpInfo.state'),
        ),
    ]
